name: controle_assinatura
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  device_preview: ^1.0.0
  fl_chart: ^0.70.2
  provider: ^6.1.4
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/MatheusReis.jpg
    - assets/images/RafaelMartins.jpg
