// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Y8uzHkdteC8ltyCcPSnOHoTzxRQGQuM',
    appId: '1:898670174538:web:e5039d227be8f148b1a1b3',
    messagingSenderId: '898670174538',
    projectId: 'gerenciador-assinatura',
    authDomain: 'gerenciador-assinatura.firebaseapp.com',
    storageBucket: 'gerenciador-assinatura.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZu8JEZdQQiFQoppcmwoY-dSClNMnUZm4',
    appId: '1:898670174538:android:e5657dd9d35dbe7eb1a1b3',
    messagingSenderId: '898670174538',
    projectId: 'gerenciador-assinatura',
    storageBucket: 'gerenciador-assinatura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjhlEMEhoFNLlSneNtr2ptZ4CYk70k8Dg',
    appId: '1:898670174538:ios:2738da819763a991b1a1b3',
    messagingSenderId: '898670174538',
    projectId: 'gerenciador-assinatura',
    storageBucket: 'gerenciador-assinatura.firebasestorage.app',
    iosBundleId: 'com.example.controleAssinatura',
  );

}